# Generated by Django 5.0.7 on 2024-07-31 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "url",
                    models.CharField(blank=True, max_length=200, verbose_name="URL"),
                ),
                (
                    "named_url",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Named URL"
                    ),
                ),
                ("menu_name", models.CharField(max_length=200, verbose_name="Меню")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child",
                        to="main.menuitem",
                        verbose_name="Родитель",
                    ),
                ),
            ],
        ),
    ]
