# Generated by Django 5.0.7 on 2024-07-31 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
            ],
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="menu_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="main.menu",
                verbose_name="Меню",
            ),
        ),
    ]
